services:
  - type: web
    name: feedbackpro-backend
    runtime: node
    plan: free
    buildCommand: npm install --production && npx esbuild server/index.production.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: node dist/index.production.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_SERVICE_ACCOUNT_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false